### ISSUE TITLE
[Card] Add optional Tag Group

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#6332]
## Detailed description

> Describe in detail the issue you're having.

I have the working code to add TagGroup to Card, however we need to solve an odd bug when running the jest tests and make sure this doesn't affect the compilation of the React package outside of Card.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
More of a bug, since the working code is ready to be implemented.

> Is this issue related to a specific component?
Card.

## Steps to reproduce the issue

1. Add working code
2. Run `yarn test:unit:updateSnapshot` in the React package directory

## Additional information
Jest error:
```
Details:

    /Users/ignacio.becerra/Documents/GitHub/ibm-dotcom-library/packages/web-components/node_modules/@babel/runtime/helpers/esm/decorate.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import toArray from "@babel/runtime/helpers/esm/toArray";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      20 | const {
      21 |   stablePrefix: ddsPrefix
    > 22 | } = ddsSettings;
         |                                     ^
      23 | const {
      24 |   prefix
      25 | } = settings;

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (../web-components/es/components/tag-group/tag-group.js:22:41)
```

**Comment by shixiedesign** [comment]
I see "Add tag" option working in Card storybook. Is this still an issue? @IgnacioBecerra

**Comment by kennylam** [comment]
@IgnacioBecerra what is the code that was added that causes the snapshot error?

**Comment by IgnacioBecerra** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6215/commits/6b6a7302e7979e85f74291d37a3d000e82a0ce59

This is the code that originally gave out the error, note that this compiles fine locally but it's just the snapshot error that prevents this from compiling the deploy preview/merging.
